var dataSet = [
    [
      "",
      "",
      "The bloody Bozeman : the perilous trail to Montana's gold",
      "Dorothy M.",
      "Johnson",
      "book",
      "non-fiction",
      "208891",
    ],
    [
      "",
      "",
      "Western badmen",
      "Dorothy M.",
      "Johnson",
      "book",
      "non-fiction",
      "96531",
    ],
    [
      "",
      "",
      "The Battle of the Little Bighorn",
      "Mari",
      "Sandoz",
      "book",
      "non-fiction",
      "328476",
    ],
    [
      "",
      "",
      "\"I will fight no more forever\"; Chief Joseph and the Nez Perce War",
      "Merrill D.",
      "Beal",
      "book",
      "non-fiction",
      "420111",
    ],
    [
      "",
      "",
      "Wolf Willow : a history, a story, and a memory of the last Plains frontier",
      "Wallace",
      "Stegner",
      "book",
      "non-fiction",
      "480307",
    ],
    [
      "",
      "",
      "Zen and the art of motorcycle maintenance: an inquiry into values",
      "Robert M.",
      "Pirsig",
      "book",
      "non-fiction",
      "673595",
    ],
    [
      "",
      "",
      "A river runs through it and other stories",
      "Norman",
      "Maclean",
      "book",
      "fiction",
      "1733412",
    ],
    [
      "",
      "",
      "James J. Hill and the opening of the Northwest",
      "Albro",
      "Martin",
      "book",
      "non-fiction",
      "2548433",
    ],
    [
      "",
      "",
      "The surrounded",
      "D'Arcy",
      "McNickle",
      "book",
      "fiction",
      "3559598",
    ],
    [
      "",
      "",
      "Fly the biggest piece back",
      "Steve",
      "Smith",
      "book",
      "non-fiction",
      "5101738",
    ],
    [
      "",
      "",
      "The last best place : a Montana anthology",
      "William",
      "Kittredge",
      "book",
      "non-fiction",
      "18322146",
    ],
    [
      "",
      "",
      "The big sky : a novel",
      "A. B.",
      "Guthrie",
      "book",
      "fiction",
      "49356082",
    ],
    [
      "",
      "",
      "Young men & fire",
      "Norman",
      "Maclean",
      "book",
      "non-fiction",
      "25630633",
    ],
    [
      "",
      "",
      "The horse whisperer",
      "Nicholas",
      "Evans",
      "book",
      "fiction",
      "32466529",
    ],
    [
      "",
      "",
      "More than petticoats, Remarkable Montana women",
      "Gayle Corbett",
      "Shirley",
      "book",
      "non-fiction",
      "32820847",
    ],
    [
      "",
      "",
      "Bucking the sun : a novel",
      "Ivan",
      "Doig",
      "book",
      "fiction",
      "34114146",
    ],
    [
      "",
      "",
      "Mavericks : the lives and battles of Montana's political legends",
      "John",
      "Morrison",
      "book",
      "non-fiction",
      "36083675",
    ],
    [
      "",
      "",
      "Dinosaur lives : unearthing an evolutionary saga",
      "John R.",
      "Horner",
      "book",
      "non-fiction",
      "36543406",
    ],
    [
      "",
      "",
      "A River runs through it",
      "Robert",
      "Redford",
      "movie",
      "fiction",
      "42955743",
    ],
    [
      "",
      "",
      "The discovery of Yellowstone Park; journal of the Washburn Expedition to the Yellowstone and Firehole Rivers in the year 1870",
      "Nathaniel Pitt",
      "Langford",
      "book",
      "non-fiction",
      "940541230",
    ],
    [
      "",
      "",
      "Monte Dolack : the works",
      "Monte",
      "Dolack",
      "book",
      "non-fiction",
      "45133743",
    ],
    [
      "",
      "",
      "Dinosaurs under the Big Sky",
      "John R.",
      "Horner",
      "book",
      "non-fiction",
      "47238733",
    ],
    [
      "",
      "",
      "Montana, high, wide, and handsome",
      "Joseph Kinsey",
      "Howard",
      "book",
      "non-fiction",
      "3648026",
    ],
    [
      "",
      "",
      "Death of a dude : A Nero Wolfe mystery",
      "Rex",
      "Stout",
      "book",
      "fiction",
      "29338",
    ],
    [
      "",
      "",
      "Montana Indians : their history and location",
      "Division of Indian Education",
      "State of Montana",
      "e-publication",
      "non-fiction",
      "82528339",
    ],
    [
      "",
      "",
      "The masterworks of Charles M. Russell : a retrospective of paintings and sculpture",
      "Joan Carpenter",
      "Troccoli",
      "book",
      "non-fiction",
      "317288402",
    ],
    [
      "",
      "",
      "Missoula",
      "Philip",
      "Maechling",
      "book",
      "non-fiction",
      "535495449",
    ],
    [
      "",
      "",
      "Hiking Montana's Bob Marshall Wilderness : including Jewel Basin and the Scapegoat and Great Bear Wilderness areas",
      "Erik",
      "Molvar",
      "book",
      "non-fiction",
      "45661743",
    ],
    [
      "",
      "",
      "The Hiker's guide to Montana",
      "Bill",
      "Schneider",
      "book",
      "non-fiction",
      "34209253",
    ],
    [
      "",
      "",
      "Charles M. Russell : photographing the legend : a biography in words and pictures",
      "Larry Len",
      "Peterson",
      "book",
      "non-fiction",
      "861209609",
    ]
];
