var dataSet = [
    [
      "",
      "The bloody Bozeman : the perilous trail to Montana's gold",
      "Dorothy M.",
      "Johnson",
    ],
    [
      "",
      "Western badmen",
      "Dorothy M.",
      "Johnson",
    ],
    [
      "",
      "The Battle of the Little Bighorn",
      "Mari",
      "Sandoz",
    ],
    [
      "",
      "\"I will fight no more forever\"; Chief Joseph and the Nez Perce War",
      "Merrill D.",
      "Beal",
    ],
    [
      "",
      "Wolf Willow : a history, a story, and a memory of the last Plains frontier",
      "Wallace",
      "Stegner",
    ],
    [
      "",
      "Zen and the art of motorcycle maintenance: an inquiry into values",
      "Robert M.",
      "Pirsig",
    ],
    [
      "",
      "A river runs through it and other stories",
      "Norman",
      "Maclean",
    ],
    [
      "",
      "James J. Hill and the opening of the Northwest",
      "Albro",
      "Martin",
    ],
    [
      "",
      "The surrounded",
      "D'Arcy",
      "McNickle",
    ],
    [
      "",
      "Fly the biggest piece back",
      "Steve",
      "Smith",
    ],
    [
      "",
      "The last best place : a Montana anthology",
      "William",
      "Kittredge",
    ],
    [
      "",
      "The big sky : a novel",
      "A. B.",
      "Guthrie",
    ],
    [
      "",
      "Young men & fire",
      "Norman",
      "Maclean",
    ],
    [
      "",
      "The horse whisperer",
      "Nicholas",
      "Evans",
    ],
    [
      "",
      "More than petticoats, Remarkable Montana women",
      "Gayle Corbett",
      "Shirley",
    ],
    [
      "",
      "Bucking the sun : a novel",
      "Ivan",
      "Doig",
    ],
    [
      "",
      "Mavericks : the lives and battles of Montana's political legends",
      "John",
      "Morrison",
    ],
    [
      "",
      "Dinosaur lives : unearthing an evolutionary saga",
      "John R.",
      "Horner",
    ],
    [
      "",
      "A River runs through it",
      "Robert",
      "Redford",
    ],
    [
      "",
      "The discovery of Yellowstone Park; journal of the Washburn Expedition to the Yellowstone and Firehole Rivers in the year 1870",
      "Nathaniel Pitt",
      "Langford",
    ],
    [
      "",
      "Monte Dolack : the works",
      "Monte",
      "Dolack",
    ],
    [
      "",
      "Dinosaurs under the Big Sky",
      "John R.",
      "Horner",
    ],
    [
      "",
      "Montana, high, wide, and handsome",
      "Joseph Kinsey",
      "Howard",
    ],
    [
      "",
      "Death of a dude : A Nero Wolfe mystery",
      "Rex",
      "Stout",
    ],
    [
      "",
      "Montana Indians : their history and location",
      "Division of Indian Education",
      "State of Montana",
    ],
    [
      "",
      "The masterworks of Charles M. Russell : a retrospective of paintings and sculpture",
      "Joan Carpenter",
      "Troccoli",
    ],
    [
      "",
      "Missoula",
      "Philip",
      "Maechling",
    ],
    [
      "",
      "Hiking Montana's Bob Marshall Wilderness : including Jewel Basin and the Scapegoat and Great Bear Wilderness areas",
      "Erik",
      "Molvar",
    ],
    [
      "",
      "The Hiker's guide to Montana",
      "Bill",
      "Schneider",
    ],
    [
      "",
      "Charles M. Russell : photographing the legend : a biography in words and pictures",
      "Larry Len",
      "Peterson",
    ]
];


